version: "3.8"

services:

  app:
    container_name: "hayat_app"
    image: hayat_app:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
      - mongo
    networks:
      - hayat_external
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  redis:
    container_name: "hayat_redis"
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    container_name: "hayat_mysql"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - hayat_db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

  mongo:
    image: mongo:latest
    container_name: "hayat_mongodb"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - hayat_mongodb:/data/db
    ports:
      - ${MONGO_PORT}:27017

volumes:
  hayat_db:
  hayat_keycloak:
  hayat_mongodb:
  hayat_postgres:
networks:
  hayat_internal:
    internal: true
  hayat_external:
    internal: false
